name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          bump-minor-pre-major: true
          changelog-types: |
            feat: Features
            fix: Bug Fixes
            docs: Documentation
            style: Styles
            refactor: Code Refactoring
            perf: Performance Improvements
            test: Tests
            chore: Chores
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version in .csproj
        run: |
          VERSION=$(cat VERSION)
          echo "New version is $VERSION"
          sed -i "s|<Version>.*</Version>|<Version>$VERSION</Version>|" **/*.csproj

      - name: Commit updated .csproj file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add **/*.csproj
          git commit -m "chore: bump version to $VERSION"
          git push
